### PR TITLE
added metanoia colorscheme

### PR DESCRIPTION
**Pull request by sinuheshinbr**

### CODE REVIEW

**Comment by linuxdotexe** [comment]
I could be wrong, but I think you should generate the colorscheme.vim file too for the new color scheme (in this case, `metanoia.vim`) using the `generate` script in the repo. Also, please add VimWiki support. The highlight groups are in all the other color schemes you can just copy them from any colorscheme.yml, paste them in yours and assign the appropriate colors. The VimWiki support part is totally upto you though, I suggested it since all the other colorschemes have it 😃

**Comment by sinuheshinbr** [comment]
Yeah, you are right, forgot about that. Generated the file and added support for VimWiki now =).

**Comment by linuxdotexe** [comment]
I can't see the VimWiki highlights in the yaml file... If you added them directly to `metanoia.vim`, when someone makes changes to the yaml files, the code that is exclusively in `metanoia.vim` will be erased. I did the same mistake with making the VimWiki Headers bold in the .vim files and before I realized I can do it from the yaml file, my request was merged. Now I made another PR and been waiting since :(( 

PS: Consider making the headers bold. I thought it looks good but it's totally upto you 😃

**Comment by sinuheshinbr** [comment]
I added bold headers and fixed yml file. I've changed in yml don't know what happened in the last commit, I tought the VimWiki highlights were there.

**Pull request merged**
